spring.application.name=store

spring.redis.host=localhost
spring.redis.port=6379

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

video.upload.path=D:/New folder (2)/store/videos/uploads
video.processed.path=D:/New folder (2)/store/videos/processed
video.thumbnail.path = D:/New folder (2)/store/videos/thumbnails

stripe.publishable.key=pk_test_51TsfsDAisXNEoc3iYHDZySBoesVdjOxyVLFDIwPdiLbSvf2uTx6W8A6R1qMFcvICY5pyj5CvBGPMlMdTp62DzjvE00bpqhyEbu
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.plan.basic = price_1TtLO8AisXNEoc3iYZAZmvkX
stripe.plan.premium = price_1TtLOdAisXNEoc3iXer5WNzN
stripe.plan.VIP = price_1TtMNNAisXNEoc3iEwp8C0oG